services:
  jekyll:
    image: jekyll/jekyll:4.2.2
    platform: linux/amd64
    command: jekyll serve --force_polling --drafts --trace
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
